- name: "Update packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install Python"
  become: yes
  apt:
    name: python
    state: latest
    update_cache: yes

- name: "Install nodejs, npm"
  become: yes
  apt:
    name: ['nodejs','npm']
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present