- name: "create a web directory"
  file:
    path: ~/web
    state: directory

- name: "unarchive and extract artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "start pm2 for npm"
  shell:
    cmd: |
      pm2 stop default
      pm2 start npm -- start
    chdir: ~/web/dist

- name: "Pause a few seconds until the app starts"
  pause: 
    seconds: 100