- name: "create a web directory"
  file:
    path: ~/web
    state: directory

- name: "unarchive and extract artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Sleep for 300 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 150

- name: "Install packages from one place"
  become: yes
  npm:
    name: [nodejs, pm2]
    global: yes
    production: yes
    state: present

- name: "restart server"
  shell: |
    pm2 start npm -- start