- name: "create a web directory"
  file:
    path: ~/web
    state: directory

- name: "unarchive and extract artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "restart pm2 service"
  shell: |
    pm2 start npm -- start