- name: "stop any process that might lock further apt installs"
  become: yes
  shell: |
    killall -9 apt-get || true

- name: "update apt packages."
  become: yes
  apt:
     update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install nodjs"
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: "install npm command line tools"
  become: yes
  apt:
    name: npm 
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create a web directory"
  file:
    path: ~/web
    state: directory

- name: "unarchive and extract artifict"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "stop server"
  shell: |
    pm2 stop default

- name: "restart server"
  shell: |
    pm2 start npm -- start