- name: "create a web directory"
  file:
    path: ~/web
    state: directory

- name: "unarchive and extract artifict"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "restart server"
  shell: |
    pm2 start npm -- start