- name: "Install nodejs"
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: "create a web directory"
  file:
    path: ~/web
    state: directory

- name: "Install npm"
  become: yes
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: "unarchive and extract artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "restart server"
  shell: |
    pm2 start npm -- start